### ISSUE TITLE
If the admin sends the bot out of the voice channel, it won't come back. 

### ISSUE THREAD

**Issue by Hjoey0904** [Matei9721/js-discord-bot#6]
If the admin sends the bot out of the voice channel, it won't come back.
Press !play to reenter or add the !join command.

**Comment by Hjoey0904** [comment]
I didn't know there was an oh command, but it doesn't work. It must be my problem.

**Comment by Matei9721** [comment]
Hey @Hjoey0904, that's a known bug for which we actually had a fix until we found out that was unstable and it resulted in the bot leaving the channel when the user also left. 

Unfortunately, I think the current code on the repository is a bit outdated compared to what I currently run hosted. Ideally, at some point, I'll have some time to refactor all the code, make it less of a cluster fuck, and fix some of the other known bugs.

As a quick fix, if the admin kicks the bot off the voice channel and you want it back you can just type `\leave` which should then remove the reference to the voice connection of the bot. After that you can do `\play song name` and it will create a new voice connector and enter the channel. If I find a good solution for this issue I'll make a PR.

**Comment by Matei9721** [comment]
@Hjoey0904 In the refactor-fixes branch you can find a fix to the bot bugging when being kicked out of the server. The code is not pushed to Master yet as it's not the final version, but you can see the code and copy it to your local version if you wish until we do the final merge.

https://github.com/Matei9721/js-discord-bot/blob/0770ef361df4fd6a0b3886791a120ab9392cd9f0/index.js#L25
